# **********************************************************************
# *
# * PostGIS - Spatial Types for PostgreSQL
# * http://postgis.net
# *
# * Copyright (C) 2020-2022 Sandro Santilli <strk@kbt.io>
# *
# * This is free software; you can redistribute and/or modify it under
# * the terms of the GNU General Public Licence. See the COPYING file.
# *
# **********************************************************************

top_srcdir = ../..
srcdir = .
builddir = .
top_builddir = ../..

PERL=/usr/bin/perl

include $(srcdir)/tests.mk
include $(top_srcdir)/regress/runtest.mk

check: check-regress
