include ./../Makefile.local
DBLATEX_EXTRA_OPTIONS = -b xetex
DOCSUFFIX=-ko_KR
srcdir=.

postgis-${POSTGIS_MAJOR_VERSION}.${POSTGIS_MINOR_VERSION}.${POSTGIS_MICRO_VERSION}$(DOCSUFFIX).pdf: texstyle.sty
